<?php
/**
* Pacific NM (https://www.pacificnm.com)
*
* @link      https://github.com/pacificnm/pacificnm-history for the canonical source repository
* @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
* @license BSD-3-Clause
*/
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate($this->layout()->pageTitle); ?> 
					<small><?php echo $this->translate("Page"); ?>: <?php echo $this->page; ?></small>
				</h3>
				<div class="box-tools">
					<?php echo $this->searchButton("history-search"); ?>
				</div>
			</div> 
            <?php if($this->paginator->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p>
						<i class="fa fa-info-circle" aria-hidden="true"></i> 
						<?php echo $this->translate("No entities found"); ?>
					</p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body  no-padding">
				<div class="row">
					<div class="col-xs-12">
						<table class="table table-bordered table-hover table-striped table-condensed">
							<thead>
								<tr>
                                    <th><?php echo $this->translate("Auth"); ?></th>
                                    <th><?php echo $this->translate("Time"); ?></th>
                                    <th><?php echo $this->translate("Request"); ?></th>
                                    <th><?php echo $this->translate("Type"); ?></th>
                                    <th><?php echo $this->translate("Ip Address"); ?></th>
                                </tr>
							</thead>
							<tbody>
							<?php foreach($this->paginator as $entity): ?>
								<tr>
									<td><?php if($entity->getAuthId() > 0): ?>
										<a href="<?php echo $this->url("auth-view", array("id" => $entity->getAuthId())); ?>" title="<?php echo $this->translate("View"); ?>">
											<?php echo $entity->getAuthEntity()->getAuthEmail(); ?>
										</a>
										<?php else: ?>
										<?php echo $this->translate("Guest"); ?>
										<?php endif; ?>
									</td>
									<td><a href="<?php echo $this->url("history-view", array("id" => $entity->getHistoryId())); ?>" title="<?php echo $this->translate("View"); ?>">
											<?php echo date($this->appConfig()->getConfigDateLong(), $entity->getHistoryRequestTime()); ?>
										</a>
									</td>
									<td><?php echo $entity->getHistoryRequest(); ?></td>
									<td><?php echo $entity->getHistoryRequestType(); ?></td>
									<td><?php echo $entity->getHistoryRemoteAddress(); ?></td>
                                </tr>
                            <?php endforeach; ?>
							</tbody>
						</table>
					</div>
				</div>
				
				<div class="row">
					<div class="col-xs-12 text-center">
						<?php echo $this->Paginator(
							$this->itemCountPerPage, 
							$this->itemCount, 
							$this->pageCount, 
                            $this->page, 
                            $this->routeParams,
                            $this->queryParams);
                        ?>
					</div>
				</div>
			</div>
			<?php endif;?>
		</div>
	</div>
</div>

<?php echo $this->historySearchForm($this->queryParams); ?>